// src/constants/serviceLinks.ts

export const serviceLoginLinks: Record<string, string> = {
    '넷플릭스': 'https://www.netflix.com/kr/Login',
    '왓챠': 'https://watcha.com/sign_in',
    '티빙': 'https://www.tving.com/account/login',
    '웨이브': 'https://www.wavve.com/member/login',
    '애플 티비': 'https://tv.apple.com/kr',
    '디즈니 플러스': 'https://www.disneyplus.com/identity/login',
    '유투브 프리미엄': 'https://accounts.google.com/v3/signin/identifier?continue=https%3A%2F%2Fwww.youtube.com%2Fsignin%3Faction_handle_signin%3Dtrue%26app%3Ddesktop%26hl%3Dko%26next%3Dhttps%253A%252F%252Fwww.youtube.com%252F%253Fhl%253Dko%2526gl%253DKR%2526app%253Ddesktop&ec=65620&hl=ko&ifkv=ASKV5MiOf3jlPy30JH5oc9F3GE6ClOuhPiNMnS6PA972zT_gGKC9C4rKUg-uea8KMoC7Xp5j_XsZPw&passive=true&service=youtube&uilel=3&flowName=GlifWebSignIn&flowEntry=ServiceLogin&dsh=S-1760556799%3A1745936595567807',
    '스포티비 나우': 'https://www.spotvnow.co.kr/login',
    '멜론': 'https://member.melon.com/muid/web/login/login_inform.htm',
    '벅스': 'https://music.bugs.co.kr',
    '지니뮤직': 'https://www.genie.co.kr/member/popLogin',
    '네이버 VIBE': 'https://nid.naver.com/nidlogin.login?url=https%3A%2F%2Fvibe.naver.com',
    '플로': 'https://www.music-flo.com/member/signin',
    '스포티파이': 'https://accounts.spotify.com/ko/login',
    '애플 뮤직': 'https://music.apple.com/kr',
    '유투브 뮤직': 'https://accounts.google.com/v3/signin/identifier?continue=https%3A%2F%2Fwww.youtube.com%2Fsignin%3Faction_handle_signin%3Dtrue%26app%3Ddesktop%26hl%3Dko%26next%3Dhttps%253A%252F%252Fwww.youtube.com%252Fmusicpremium&ec=65620&hl=ko&ifkv=ASKV5MhkGgnwTVBWb06M1q9nGknQau4geFRPdexC_pdeBHUpWMj6rx5q5nr_70qs4zzXljv0YvExbg&passive=true&service=youtube&uilel=3&flowName=GlifWebSignIn&flowEntry=ServiceLogin&dsh=S1696301245%3A1745937087712190/',
    '요기패스': 'https://www.yogiyo.co.kr/mobile/#/login',
    '배민클럽': 'https://biz-member.baemin.com/login',
    '컬리': 'https://www.kurly.com/member/login',
    'CJ 더마켓': 'https://www.cjthemarket.com',
    '지마켓': 'https://mobile.gmarket.co.kr/Login/Login',
    '클로젯쉐어': 'https://www.closetshare.com/theclozet/front/member/loginForm',
    '더 한섬': 'https://m.thehandsome.com/ko/ME/login',
    '구글 드라이브': 'https://accounts.google.com/v3/signin/identifier?ifkv=ASKV5Mjl6jRXAHol38f0do_aADgIZ6hLeqMFM1XrUi_q-6qQlYlm-mWH58goQWnmDyyPtoypxRjQ&rip=1&sacu=1&service=writely&flowName=GlifWebSignIn&flowEntry=ServiceLogin&dsh=S1445109615%3A1745937136202705/',
    '원드라이브': 'https://onedrive.live.com/login',
    '드랍박스': 'https://www.dropbox.com/login',
    '박스': 'https://account.box.com/login',
    '한컴독스': 'https://accounts.hancom.com/oauth2/authorize?...',
    '구글 코랩': 'https://accounts.google.com/v3/signin/accountchooser?continue=https%3A%2F%2Fcolab.research.google.com%2F...',
    '챗지피티': 'https://auth.openai.com/log-in',
    '제미나이': 'https://accounts.google.com/v3/signin/identifier?...',
    '미드저니': 'https://www.midjourney.com/home',
    '이디오그램': 'https://ideogram.ai/t/explore',
    '클로드': 'https://claude.ai/login',
    '딥엘': 'https://www.deepl.com/ko/login',
    '그래멀리': 'https://www.grammarly.com/signin',
    '감마': 'https://gamma.app/signin',
    '릴리스AI': 'https://lilys.ai',
    '클로바노트': 'https://nid.naver.com/nidlogin.login?url=https%3A%2F%2Fclovanote.naver.com',
    '포토샵': 'https://auth.services.adobe.com/ko_KR/index.html?...',
    '애프터이팩트': 'https://auth.services.adobe.com/ko_KR/index.html?...',
    '피그마': 'https://www.figma.com/login',
    '캔바': 'https://www.canva.com/ko_kr',
    '노션': 'https://www.notion.so/login',
    '스케치': 'https://www.sketch.com/signin',
    '슬랙': 'https://slack.com/signin',
    '마이크로소프트 365': 'https://login.microsoftonline.com/',
    '애플아케이드': 'https://account.apple.com/sign-in',
    '구글 플레이 패스': 'https://accounts.google.com/v3/signin/accountchooser?continue=https%3A%2F%2Fplay.google.com%2Fweb%2Fstore...',
    '와우멤버쉽': 'https://login.coupang.com/login/login.pang',
    '이모티콘 플러스': 'https://accounts.kakao.com/login/?continue=https%3A%2F%2Fmy.kakao.com%2Fproduct-group%2FEMOTICON',
    '네이버 플러스': 'https://nid.naver.com/nidlogin.login?mode=form&url=https%3A%2F%2Fnid.naver.com%2Fmembership',
    '줌': 'https://www.zoom.us/ko/signin#/login'
};